language: node_js

node_js:
  - "12"
  - "10"
  - "8"
  - "6"

os:
  - linux
  - osx

install:
  - npm install

script:
  - node --version
  - npm --version
  - npm run test-non-windows

after_success:
  - npm run coverage-codecov

notifications:
  email: false
