language: node_js
node_js:
  - "10"
  - "8"
  - "6"
  - "4"
os:
  - linux
  - osx
install:
  - npm install
script:
  - npm run test-non-windows
after_success:
  - npm run coverage
notifications:
  email: false
